# Generated by Django 3.0.3 on 2020-02-23 10:08

from django.db import migrations, models
import image.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('picture', models.FileField(blank=True, null=True, upload_to=image.models.get_upload_file_name)),
                ('pub_date', models.DateTimeField(null=True, verbose_name='date_published')),
            ],
        ),
    ]
