# Generated by Django 3.0.3 on 2020-02-24 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('hotel_Main_Img', models.ImageField(upload_to='images/')),
                ('pub_date', models.DateTimeField(null=True, verbose_name='date_published')),
            ],
        ),
    ]
