# Generated by Django 3.0.3 on 2020-02-24 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0002_hotel'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('file', models.FileField(upload_to='')),
            ],
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='hotel_Main_Img',
        ),
        migrations.AddField(
            model_name='hotel',
            name='ImagePath',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='pub_date',
            field=models.DateTimeField(null=True),
        ),
    ]
